### PR TITLE
Fix Invalid input causes SegFault

### LINKED ISSUE #13: Segfault on invalid input to loads
```
$ python
Python 3.6.9 (default, Nov  6 2019, 09:59:57)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pghstore
>>> pghstore.loads(b'"key"=>NULL"')
Segmentation fault: 11
```

### PR DESCRIPTION
**Pull request by lambacck**
Closes #13 

Fixing the segfault also revealed problems with invalid input that didn't raise exceptions. This increases coverage for invalid input cases. This may need to have a more significant version bump associated with it since it raises ValueError more often.

### CODE REVIEW

File: src/pghstore/_speedups.c [hunk 1]
```diff
@@ -35,16 +31,22 @@ struct module_state {
  * Just like strchr, but find first -unescaped- occurrence of c in s.
  */
 char *
-strchr_unescaped(char *s, char c) 
+strchr_unescaped(char *s, Py_ssize_t length, char c) 
 {
-  char *p = strchr(s, c), *q;
+  char *end = s + length;
+  debug_print( "looging for p: s[%c, %p]\n", *s,  s);
```
Comment (sigmavirus24) [inline src/pghstore/_speedups.c:37]: looging?

**Comment by lambacck** [comment]
The last test failure I fixed makes me feel like we need way more test cases to be sure it's all working correctly.

**Comment by sigmavirus24** [comment]
Hence https://github.com/heroku/pghstore/issues/15
